
import { Job } from './types';

export const JOB_CATEGORIES: string[] = [
    'בייביסיטר',
    'שיעורים פרטיים',
    'מלצרות',
    'טיפול בבעלי חיים',
    'ניקיון',
    'שליחויות',
    'עזרה טכנית',
    'מכירות',
];

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'מלצר/ית לאירוע ערב',
    employer: { id: 'e1', name: 'קייטרינג "השף הצוחק"', rating: 4.8 },
    location: 'תל אביב',
    category: 'מלצרות',
    description: 'דרושים מלצרים זריזים וחייכנים לאירוע חברה יוקרתי במרכז תל אביב. עבודה כיפית באווירה טובה.',
    hourlyRate: 45,
    isUrgent: true,
    tags: ['גמיש', 'טיפים'],
  },
  {
    id: '2',
    title: 'בייביסיטר אנרגטי/ת',
    employer: { id: 'e2', name: 'משפחת כהן', rating: 5.0 },
    location: 'רעננה',
    category: 'בייביסיטר',
    description: 'מחפשים בייביסיטר לשני ילדים מקסימים בני 6 ו-8. נדרשת אחריות, סבלנות ויצירתיות.',
    hourlyRate: 40,
    isUrgent: false,
    tags: ['אחה"צ', 'קבוע'],
  },
  {
    id: '3',
    title: 'דוגווקר/ית אוהב/ת כלבים',
    employer: { id: 'e3', name: 'מיכל לוי', rating: 4.9 },
    location: 'חיפה',
    category: 'טיפול בבעלי חיים',
    description: 'דרוש/ה נער/ה אחראי/ת להוציא את רקס, כלב לברדור חמוד, לשלושה טיולים ביום.',
    hourlyRate: 35,
    isUrgent: false,
    tags: ['בעלי חיים', 'חוץ'],
  },
  {
    id: '4',
    title: 'עזרה בהכנת שיעורי בית במתמטיקה',
    employer: { id: 'e4', name: 'משפחת אדרי', rating: 4.7 },
    location: 'ירושלים',
    category: 'שיעורים פרטיים',
    description: 'דרוש/ה חונכ/ת עם ראש על הכתפיים לעזרה בשיעורי בית במתמטיקה לתלמיד כיתה ח\'.',
    hourlyRate: 50,
    isUrgent: true,
    tags: ['לימודים', 'שקט'],
  },
  {
    id: '5',
    title: 'סידור סחורה בחנות אופנה',
    employer: { id: 'e5', name: 'בוטיק "סטייל"', rating: 4.5 },
    location: 'הרצליה',
    category: 'מכירות',
    description: 'לחנות בוטיק מדליקה דרושים/ות נערים/ות לסידור סחורה, קיפול בגדים ועזרה כללית.',
    hourlyRate: 38,
    isUrgent: false,
    tags: ['אופנה', 'משמרות'],
  },
  {
    id: '6',
    title: 'עזרה בניקיון וסידור הגינה',
    employer: { id: 'e6', name: 'דניאל גרין', rating: 4.9 },
    location: 'כפר סבא',
    category: 'ניקיון',
    description: 'מחפש/ת נער/ה חרוצ/ה לעזרה בגינון, ניכוש עשבים וסידור כללי של הגינה. לא נדרש ניסיון קודם.',
    hourlyRate: 42,
    isUrgent: false,
    tags: ['פיזי', 'גינון'],
  },
];
